apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-qmsaxceh
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-qmsaxceh:947c50e5e661adcc7eaf431c35b47a738e1c9854@sha256:13fd126721efe16530d817900ba4c55ad46436f91ff4691c0ca6a0e56ff494bd
        name: container-image  
